version: '3.4'

services:
  gatewayapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  profile:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  questions:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

