version: '3.4'

networks:
    backend: {}             
    database: {}        
    cachenetwork: {}
             
    
services:
       
    mongodb:
        image: mongo 
        container_name: mongolocal 
        networks:
            database: 
                aliases: 
                    - mongo
  
    rabbitmq:
        image: rabbitmq:3-management    
        container_name: rabbitmq
        networks: 
            backend:
                aliases:
                    - localrabbit
                    
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.2
        container_name: elasticsearch             
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        networks:
            database:
                aliases:
                    - elasticsearch
        
    graylog:
        image: graylog/graylog:3.0
        container_name: graylog       
        environment:
            - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
            # Password: admin
            - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
            - GRAYLOG_REST_TRANSPORT_URI=http://127.0.0.1:9000 
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
        links:
            - mongodb:mongo
            - elasticsearch
        depends_on:
            - mongodb
            - elasticsearch
        ports:
            # Graylog web interface and REST API
            - 9000:9000
            # Syslog TCP
            - 514:514
            # Syslog UDP
            - 514:514/udp
            # GELF TCP
            - 12201:12201
            # GELF UDP
            - 12201:12201/udp
        networks:
            database:  
                aliases:
                    - graylog             
            
    gatewayapi:
        image: ${DOCKER_REGISTRY-}gatewayapi
        container_name: gateway
        build:
            context: .
            dockerfile: GatewayAPI/Dockerfile
        networks:
            - backend
            - database
            - cachenetwork
        
    profile:
        image: ${DOCKER_REGISTRY-}profile    
        container_name: profileapi
        build:
            context: .
            dockerfile: Profile/Dockerfile
        networks:
            database: 
            cachenetwork: 
            backend: 
                aliases: 
                    - profileapi                    
       
 
    questions:
        image: ${DOCKER_REGISTRY-}questions
        container_name: questionapi
        build:
            context: .
            dockerfile: Questions/Dockerfile  
        networks:
            database: 
            cachenetwork: 
            backend: 
                aliases: 
                    - questionapi
                    
        